spring:
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  security:
    jwt:
      jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
      issuer: ${KEYCLOAK_ISSUER}
      audience: ${KEYCLOAK_AUDIENCE:shoponline-backend}
