-- ATS-38: Admin-curated featured products for the storefront HomePage.
ALTER TABLE PRODUCTS ADD FEATURED NUMBER(1) DEFAULT 0 NOT NULL;

ALTER TABLE PRODUCTS ADD CONSTRAINT CHK_PRODUCTS_FEATURED
    CHECK (FEATURED IN (0, 1));

CREATE INDEX IDX_PRODUCTS_FEATURED_UPDATED
    ON PRODUCTS(STATUS, FEATURED, UPDATED_AT DESC);

COMMENT ON COLUMN PRODUCTS.FEATURED IS '0=standard product, 1=featured on storefront HomePage';

COMMIT;
