-- ============================================================
-- V9__create_addresses.sql
-- Description: Create ADDRESSES table for ATS-23 multi-address delivery management
-- Relationship: CUSTOMERS 1 - N ADDRESSES
-- ============================================================

CREATE TABLE ADDRESSES (
    ADDRESS_ID     NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID    NUMBER(19)     NOT NULL,
    RECIPIENT_NAME VARCHAR2(200 CHAR) NOT NULL,
    PHONE          VARCHAR2(20 CHAR)  NOT NULL,
    LINE1          VARCHAR2(255 CHAR) NOT NULL,
    WARD           VARCHAR2(100 CHAR),
    DISTRICT       VARCHAR2(100 CHAR),
    PROVINCE       VARCHAR2(100 CHAR) NOT NULL,
    IS_DEFAULT     NUMBER(1)      DEFAULT 0 NOT NULL,
    CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     VARCHAR2(100 CHAR),
    UPDATED_BY     VARCHAR2(100 CHAR),
    CONSTRAINT FK_ADDRESSES_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_ADDRESSES_IS_DEFAULT CHECK (IS_DEFAULT IN (0, 1))
);

CREATE INDEX IX_ADDRESSES_CUSTOMER ON ADDRESSES (CUSTOMER_ID);

-- Enforce at most one default address per customer. Oracle has no partial/filtered
-- unique index syntax, so a function-based unique index is used instead: non-default
-- rows (IS_DEFAULT = 0) all evaluate to NULL and are excluded from uniqueness checks,
-- leaving only the (at most one) default row per customer subject to the constraint.
CREATE UNIQUE INDEX UX_ADDRESSES_ONE_DEFAULT
    ON ADDRESSES (CASE WHEN IS_DEFAULT = 1 THEN CUSTOMER_ID END);

COMMENT ON TABLE  ADDRESSES IS 'Customer delivery addresses. 1-N with CUSTOMERS. Free-text fields only.';
COMMENT ON COLUMN ADDRESSES.IS_DEFAULT IS '0=not default, 1=default. At most one default per customer (see UX_ADDRESSES_ONE_DEFAULT).';

COMMIT;
